import { defineConfig } from 'vite'
import type { PluginOption } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

// https://vite.dev/config/
export default defineConfig(async () => {
  const plugins: PluginOption[] = [react(), tailwindcss()];
  try {
    const sourceTagsPath = './.vite-source-tags.js';
    const m = await import(sourceTagsPath) as { sourceTags?: () => PluginOption };
    if (typeof m.sourceTags === 'function') plugins.push(m.sourceTags());
  } catch {
    // Optional local plugin generated by the app builder.
  }

  return {
    plugins,
    envPrefix: ['VITE_'],
  };
})
